#!/usr/bin/env python3
"""
Ghidra Headless Analysis Script for ELF binaries.

This script generates and executes Ghidra analysis without requiring GUI interaction.
It creates reusable Ghidra scripts for future analysis workflows.

Usage:
    python3 scripts/ghidra-report.py <ELF_BINARY> [OPTIONS]

Output Structure:
    ghidra_projects/
    ├── <project_name>/           # Ghidra project directory (created during analysis)
    └── ghidra_scripts/
        ├── embedded_analysis.py   # Main analysis script
        ├── extract_qt.py          # Qt-specific extractor
        └── extract_serial.py      # Serial/network extractor

The generated scripts use analyzeHeadless and can be run independently.
"""

from __future__ import annotations

import argparse
import json
import logging
import os
import subprocess
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional, List

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(levelname)s - %(message)s"
)
logger = logging.getLogger(__name__)


@dataclass
class GhidraConfig:
    """Configuration for Ghidra analysis."""
    ghidra_dir: Path = Path("/opt/ghidra")
    project_dir: Path = Path("ghidra_projects")
    project_name: str = ""
    binary_path: Path = Path("binary")
    output_dir: Path = Path("reports")
    analysis_timeout: int = 300
    verbose: bool = False
    skip_execution: bool = True


# ============================================================================
# Generated Ghidra Scripts
# ============================================================================

EMBEDDED_ANALYSIS_SCRIPT = '''#!/usr/bin/env python
# ------------------------------------------------------------
# embedded_analysis.py - Ghidra Headless Analysis Script
# Generated by ReLinux ELF Analysis Toolkit
# ------------------------------------------------------------
#
# Usage with analyzeHeadless:
#   analyzeHeadless <project_dir> <project_name> \\
#     -import <binary> \\
#     -postscript embedded_analysis.py \\
#     -deleteProject
#
# This script extracts embedded-specific information from ELF binaries.
# ------------------------------------------------------------

#@category Embedded Analysis
#@keybinding
#@menupath Tools.ReLinux.ELF Analysis
#@toolbar

import json

def extract_embedded_info():
    """Extract embedded-specific information from the binary."""
    listing = currentProgram.getListing()
    
    results = {
        "serial_functions": [],
        "network_functions": [],
        "qt_functions": [],
        "file_operations": [],
        "firmware_references": [],
    }
    
    serial_patterns = ["serial", "uart", "tty", "rs232", "rs485", "modbus"]
    network_patterns = ["tcp", "socket", "connect", "send", "recv", "http", "ftp"]
    qt_patterns = ["qt", "qml", "qobject", "qstring", "qwidget"]
    
    for func in listing.getFunctions(True):
        name = func.getName().lower()
        
        for pattern in serial_patterns:
            if pattern in name:
                results["serial_functions"].append(func.getName())
                break
        
        for pattern in network_patterns:
            if pattern in name:
                results["network_functions"].append(func.getName())
                break
        
        for pattern in qt_patterns:
            if pattern in name:
                results["qt_functions"].append(func.getName())
                break
    
    return results

def main():
    results = extract_embedded_info()
    
    output_file = currentProgram.getExecutablePath() + ".ghidra_analysis.json"
    with open(output_file, "w") as f:
        json.dump(results, f, indent=2)
    
    println("Analysis complete: " + output_file)
'''

QT_EXTRACT_SCRIPT = '''#!/usr/bin/env python
# ------------------------------------------------------------
# extract_qt.py - Qt Class and QML Type Extractor
# Generated by ReLinux ELF Analysis Toolkit
# ------------------------------------------------------------

#@category Embedded Analysis.Qt
#@keybinding
#@menupath Tools.ReLinux.Qt Extractor

import json

def extract_qt_info():
    """Extract Qt class hierarchy and QML registrations."""
    listing = currentProgram.getListing()
    
    qt_symbols = []
    qml_types = []
    
    for symbol in getSymbolTable().getAllSymbols(True):
        name = symbol.getName()
        if "staticMetaObject" in name or "qt_static_metacall" in name:
            qt_symbols.append(name)
        
        if "qmlRegisterType" in name or "qmltype" in name.lower():
            qml_types.append(name)
    
    return {
        "qt_symbols": qt_symbols,
        "qml_types": qml_types,
    }

def main():
    results = extract_qt_info()
    output_file = currentProgram.getExecutablePath() + ".qt_analysis.json"
    with open(output_file, "w") as f:
        json.dump(results, f, indent=2)
    println("Qt analysis complete: " + output_file)
'''

SERIAL_EXTRACT_SCRIPT = '''#!/usr/bin/env python
# ------------------------------------------------------------
# extract_serial.py - Serial Port Interaction Extractor
# Generated by ReLinux ELF Analysis Toolkit
# ------------------------------------------------------------

#@category Embedded Analysis.Serial
#@keybinding
#@menupath Tools.ReLinux.Serial Extractor

import json

def extract_serial_info():
    """Extract serial port interaction patterns."""
    listing = currentProgram.getListing()
    
    serial_funcs = []
    device_paths = []
    
    for func in listing.getFunctions(True):
        name = func.getName().lower()
        
        if any(p in name for p in ["serial", "uart", "tty", "open", "close"]):
            serial_funcs.append(func.getName())
    
    for block in getMemoryBlocks():
        if block.isInitialized():
            data = block.getBytes()
            if data:
                try:
                    s = str(data)
                    if "/dev/tty" in s:
                        device_paths.append(s.strip())
                except:
                    pass
    
    return {
        "serial_functions": serial_funcs,
        "device_paths": device_paths,
    }

def main():
    results = extract_serial_info()
    output_file = currentProgram.getExecutablePath() + ".serial_analysis.json"
    with open(output_file, "w") as f:
        json.dump(results, f, indent=2)
    println("Serial analysis complete: " + output_file)
'''


class GhidraProjectGenerator:
    """Generates Ghidra project structure and analysis scripts.
    
    This class handles:
    1. Project directory structure creation
    2. Analysis script generation
    3. Execution of headless analysis (optional)
    """
    
    def __init__(self, config: GhidraConfig):
        self.config = config
        self.script_dir = config.project_dir / "ghidra_scripts"
    
    def find_ghidra(self) -> Optional[Path]:
        """Find Ghidra installation directory."""
        common_paths = [
            Path("/opt/ghidra"),
            Path("/opt/ghidra-current"),
            Path("~/ghidra"),
        ]
        
        for p in common_paths:
            expanded = p.expanduser()
            if expanded.exists():
                return expanded
        return None
    
    def create_project_structure(self) -> None:
        """Create project directory structure."""
        self.config.project_dir.mkdir(parents=True, exist_ok=True)
        self.script_dir.mkdir(parents=True, exist_ok=True)
        logger.info(f"Created project structure: {self.config.project_dir}")
    
    def generate_scripts(self) -> List[Path]:
        """Generate reusable Ghidra analysis scripts."""
        scripts = [
            ("embedded_analysis.py", EMBEDDED_ANALYSIS_SCRIPT),
            ("extract_qt.py", QT_EXTRACT_SCRIPT),
            ("extract_serial.py", SERIAL_EXTRACT_SCRIPT),
        ]
        
        generated = []
        for name, content in scripts:
            script_path = self.script_dir / name
            script_path.write_text(content.strip())
            generated.append(script_path)
            logger.info(f"Generated: {script_path}")
        
        return generated
    
    def generate_readme(self) -> None:
        """Generate README with usage instructions."""
        readme_content = f"""# Ghidra Analysis Project

## Project Structure

```
{self.config.project_dir.name}/
├── ghidra_scripts/
│   ├── embedded_analysis.py   # Main analysis script
│   ├── extract_qt.py          # Qt class extractor
│   └── extract_serial.py      # Serial port extractor
└── {self.config.project_name}/  # Created during analysis
```

## Running Headless Analysis

```bash
# Source the cross-toolchain environment
source ../fish_env

# Run headless analysis
{self.config.ghidra_dir}/support/analyzeHeadless \\
    {self.config.project_dir.name}/{self.config.project_name} \\
    {self.config.project_name} \\
    -import {self.config.binary_path} \\
    -postscript ghidra_scripts/embedded_analysis.py \\
    -deleteProject
```

## Generated Files

The scripts produce:
- `<binary>.ghidra_analysis.json` - Serial/network/Qt function analysis
- `<binary>.qt_analysis.json` - Qt class/QML type analysis  
- `<binary>.serial_analysis.json` - Serial port analysis

## Script Notes

- Scripts are idempotent - safe to run multiple times
- Output JSON files can be parsed by other tools in this toolkit
- For batch processing, wrap in a shell loop
"""
        readme_path = self.config.project_dir / "README.md"
        readme_path.write_text(readme_content)
        logger.info(f"Generated README: {readme_path}")
    
    def check_environment(self) -> bool:
        """Verify Ghidra and Java are available."""
        # Use local variable for ghidra discovery
        ghidra_found = self.config.ghidra_dir / "support" / "analyzeHeadless"
        if not ghidra_found.exists():
            found = self.find_ghidra()
            if not found:
                logger.error("Ghidra not found. Specify --ghidra-dir")
                return False
            ghidra_found = found / "support" / "analyzeHeadless"
        
        if not ghidra_found.exists():
            logger.error("analyzeHeadless script not found")
            return False
        
        # Check Java
        try:
            proc = subprocess.run(
                ["java", "-version"],
                capture_output=True,
                text=True,
                timeout=10
            )
            logger.info("Java runtime available")
        except FileNotFoundError:
            logger.error("Java not found in PATH")
            return False
        
        return True
    
    def run_analysis(self) -> bool:
        """Execute Ghidra headless analysis."""
        if self.config.skip_execution:
            logger.info("Skipping execution (--skip-execution)")
            return True
        
        analyze_script = self.config.ghidra_dir / "support" / "analyzeHeadless"
        
        cmd = [
            str(analyze_script),
            str(self.config.project_dir),
            self.config.project_name,
            "-import", str(self.config.binary_path),
            "-postscript", "embedded_analysis.py",
            "-deleteProject",
            "-noanalysis",
        ]
        
        if self.config.verbose:
            cmd.append("-verbose")
        
        logger.info(f"Running: {' '.join(cmd)}")
        
        try:
            proc = subprocess.run(
                cmd,
                capture_output=True,
                text=True,
                timeout=self.config.analysis_timeout,
                cwd=str(self.config.ghidra_dir)
            )
            
            if self.config.verbose:
                print(proc.stdout)
                if proc.stderr:
                    print(proc.stderr, file=sys.stderr)
            
            logger.info("Ghidra analysis completed")
            return True
            
        except subprocess.TimeoutExpired:
            logger.error("Ghidra analysis timed out")
            return False
        except Exception as e:
            logger.error(f"Analysis failed: {e}")
            return False


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate and run Ghidra headless analysis on ELF binaries"
    )
    parser.add_argument(
        "binary",
        type=Path,
        help="Path to the ELF binary to analyze"
    )
    parser.add_argument(
        "--ghidra-dir",
        type=Path,
        default=None,
        help="Path to Ghidra installation (auto-detected if not specified)"
    )
    parser.add_argument(
        "--project-dir",
        type=Path,
        default=Path(__file__).parent.parent / "ghidra_projects",
        help="Directory for Ghidra projects"
    )
    parser.add_argument(
        "--timeout",
        type=int,
        default=300,
        help="Analysis timeout in seconds"
    )
    parser.add_argument(
        "--execute",
        action="store_true",
        help="Execute analysis (requires Ghidra installed)"
    )
    parser.add_argument(
        "--skip-execution",
        action="store_true",
        help="Generate scripts only, do not run analysis"
    )
    parser.add_argument(
        "--verbose", "-v",
        action="store_true",
        help="Enable verbose output"
    )
    
    args = parser.parse_args()
    
    if not args.binary.exists():
        logger.error(f"Binary not found: {args.binary}")
        sys.exit(1)
    
    # Determine Ghidra directory
    ghidra_dir = args.ghidra_dir
    if ghidra_dir is None:
        common_paths = [
            Path("/opt/ghidra"),
            Path("/opt/ghidra-current"),
            Path("~/ghidra"),
        ]
        for p in common_paths:
            if p.exists():
                ghidra_dir = p.expanduser() if str(p).startswith("~") else p
                break
        
        if ghidra_dir is None and not args.skip_execution:
            logger.info("Ghidra not found - use --skip-execution to generate templates only")
    
    project_name = args.binary.stem
    
    config = GhidraConfig(
        ghidra_dir=ghidra_dir or Path("/opt/ghidra"),
        project_dir=args.project_dir,
        project_name=project_name,
        binary_path=args.binary,
        output_dir=args.project_dir.parent / "reports",
        analysis_timeout=args.timeout,
        verbose=args.verbose,
        skip_execution=args.skip_execution or not args.execute,
    )
    
    generator = GhidraProjectGenerator(config)
    generator.create_project_structure()
    generator.generate_scripts()
    generator.generate_readme()
    
    if args.execute and ghidra_dir:
        if not generator.check_environment():
            logger.error("Environment check failed")
            sys.exit(1)
        generator.run_analysis()
    
    logger.info(f"Project ready at {args.project_dir}")


if __name__ == "__main__":
    main()