#!/bin/sh

case "$1" in
    start)
        mkdir -p /sys/kernel/debug
        mountpoint -q /sys/kernel/debug || \
            mount -t debugfs debugfs /sys/kernel/debug 2>/dev/null || true
        ;;
esac

exit 0
